export const GROUPS_INIT: 'GROUPS_INIT' = 'GROUPS_INIT'

export const GROUPS_FILTER_CHANGE: 'GROUPS_FILTER_CHANGE' = 'GROUPS_FILTER_CHANGE'

export const GROUPS_CHANGE: 'GROUPS_CHANGE' = 'GROUPS_CHANGE'