export const GROUPS_INIT: 'GROUPS_INIT' = 'GROUPS_INIT'

export const GROUPS_TYPE_OF_GROUP_CHANGE: 'GROUPS_TYPE_OF_GROUP_CHANGE' = 'GROUPS_TYPE_OF_GROUP_CHANGE'
export const GROUPS_COLOR_CHANGE: 'GROUPS_COLOR_CHANGE' = 'GROUPS_COLOR_CHANGE'
export const GROUPS_WITH_FRIENDS_CHANGE: 'GROUPS_WITH_FRIENDS_CHANGE' = 'GROUPS_WITH_FRIENDS_CHANGE'

export const GROUPS_CHANGE: 'GROUPS_CHANGE' = 'GROUPS_CHANGE'